[platformio]
default_envs = esp32-s3-devkitc-1

[env:esp32-s3-devkitc-1]
platform = espressif32@6.9.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit PN532@1.3.4
  rweather/Crypto@0.4.0
build_unflags = -std=gnu++11
build_flags =
  -std=gnu++17
  -Wall
  -Wextra


[env:uid-poc]
extends = env:esp32-s3-devkitc-1
build_flags =
  ${env:esp32-s3-devkitc-1.build_flags}
  -DHERMES_AUTH_MODE_UID_POC=1

[env:secure-mock]
extends = env:esp32-s3-devkitc-1
build_flags =
  ${env:esp32-s3-devkitc-1.build_flags}
  -DHERMES_SECURE_MOCK=1
